#!/bin/env python

import os
test=['200','300','400']
t=['01','02','03','04','05','06','07','08','09','10']

for i in test:
	print "==="+i+"==="
	for j in t:
		for k in range(0,20):
			print i+"_"+j
			os.system("./csp"+i+" pb_"+i+"_"+j+".txt")
